export const CONNECT_TO_FIREBASE = "CONNECT_TO_FIREBASE"
export const CONNECT_TO_FIREBASE_SUCCESS = "CONNECT_TO_FIREBASE_SUCCESS"
export const CONNECT_TO_FIREBASE_FAILED = "CONNECT_TO_FIREBASE_FAILED"
