export const SEARCH_LOCATIONS = "SEARCH_LOCATIONS"
export const GET_CAMPAIGNS_REQUEST = "GET_CAMPAIGNS_REQUEST"
export const GET_CAMPAIGNS_SUCCESS = "GET_CAMPAIGNS_SUCCESS"
export const GET_CAMPAIGNS_FAILED = "GET_CAMPAIGNS_FAILED"
